 
 -------------- celery@EAPPLEs-MacBook-Pro.local v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- macOS-14.5-arm64-arm-64bit 2024-08-12 05:10:14
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         e_com_django:0x1022cc800
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . app_auth.controller.send_otp_email

[2024-08-12 05:10:14,991: WARNING/MainProcess] /Users/talha/Documents/personal_projects/e_com_django/env/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2024-08-12 05:10:14,998: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2024-08-12 05:10:17,016: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2024-08-12 05:10:21,039: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2024-08-12 05:10:27,067: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2024-08-12 05:10:35,100: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)


worker: Warm shutdown (MainProcess)
